package com.chemista15.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CollectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionAllPropertiesEquals(Collection expected, Collection actual) {
        assertCollectionAutoGeneratedPropertiesEquals(expected, actual);
        assertCollectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionAllUpdatablePropertiesEquals(Collection expected, Collection actual) {
        assertCollectionUpdatableFieldsEquals(expected, actual);
        assertCollectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionAutoGeneratedPropertiesEquals(Collection expected, Collection actual) {
        assertThat(expected)
            .as("Verify Collection auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionUpdatableFieldsEquals(Collection expected, Collection actual) {
        assertThat(expected)
            .as("Verify Collection relevant properties")
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionUpdatableRelationshipsEquals(Collection expected, Collection actual) {}
}
